Provider: Yaml

MySql:
  Host: "127.0.0.1"
  Port: "3306"
  User: "root"
  Database: "vouchers"
  Password: "pati_patu"

MongoDB:
  Uri: "URI_LINK"
  Database: "vouchers"

Commands:
  Voucher:
    Name: "voucher"
    Description: "Create vouchers"
  Redeem:
    Name: "redeem"
    Description: "Redeem a voucher"